name: Deploy Hexo

on:
  push:
    branches:
      - master  # 或者你用于存储源代码的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0' # 确保这个版本与你本地使用的一致

    - name: Instal node and npm
      run: |
        cd Blog/hexo-blog
        rm -rf node_modules && npm install --force

    - name: Install Hexo
      run: | 
        cd Blog/hexo-blog
        npm install -g hexo-cli

    - name: Setup yarn & Install node_modules
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install

    - name: Build
      run: |
        git config --global user.name "WangQIanyi"
        git config --global user.email "1814132364@qq.com"
        cd Blog/hexo-blog
        sed -i'' "s~${GH_TOKEN}@github.com:~https://${{ secrets.GH_TOKEN }}@github.com/~" _config.yml
        yarn clean
        yarn build

    - name: Deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "WangQIanyi"
        git config --global user.email "1814132364@qq.com"
        cd Blog/hexo-blog
        sed -i'' "s~${GH_TOKEN}@github.com:~https://${{ secrets.GH_TOKEN }}@github.com/~" _config.yml
        yarn deploy